project_name: Default
working_dir: exploration
cmd:
- python model_prediction.py
provisioning:
  gpu_type: a10g
  gpu_count: 1
  cpu_count: 32
  ram: 128
teamcity:
  url: https://mlops.staging.sandbox.teamcity.aws.intellij.net
  build_conf_id: id68eafec2fcf54184bbb253fff61d0256_JetTrain
env:
  variables:
    PYTHONUNBUFFERED: "1"
  python:
    pip:
      requirements_path: requirements.txt
    version: 3.12.3
  secrets:
    variables: {}
    ssh_keys: []
  aws:
    sync_config: false
    sync_credentials: false
    sync_cache: false
project_sync:
  local:
    root: "."
    storage_name: Cadence Storage
    uri: ""
    exclude:
    - /.venv/**
    include: []
    sync_back: false
    snapshots: true
    storage_type: DEFAULT
inputs: []
outputs:
- type: OUTPUT
  storage_name: Cadence Storage
  uri: data/1fe17bbd-463f-4a95-9661-fde5b9434ebf/snapshots/antaww/2024-12-13T16-41-87Z_01213415-0f4c-4c27-8e70-b25305c564eb/outputs/
  path: "."
  acceleration: false
  storage_type: DEFAULT
mounts: []
storages:
- name: Cadence Storage
  storage_type: s3
  credentials:
    access_key_id: ASIASYCYVCDCZNDURPFS
    secret_access_key: h0Jmb9QQpQOz1UWnIxRB46gSU7Cl8VJOjmItQz2x
    session_token: IQoJb3JpZ2luX2VjECAaCWV1LXdlc3QtMSJHMEUCIDQ81FbAlx1maST+DQcnKAW6YxSNop9DgUdH3gmG+NIEAiEA0FeHzAitsMzCYNr9hS+cN+Jbm8fX8Wls960F17cjywEqswUI2f//////////ARABGgwxODkxNjQ0OTA5NDkiDE6gJxxhpN6irTHTVSqHBdkI1Yz1XwfvSHYUj1PfKht8xpr5s9kfaVsJRqO2gHLpjMDftN59bogHzg1o93Px3MwNQUr+oBYbvXoWEOeq4cjD24VOuEl3OLyaUj2EwzFDoqBIEy9LRfQppaeq5hau1m2EFth/6oqdOTY50kXN/eYQa0dazfR1h280oBOBqcXLJfOl5/w6fv/O0LlAOtMtc0XdG0EFH7MH+Di+m3/ppCl/llaTWjn72ApfU9YaS++I7j0c+f67YKTKhC8f4ogGUyGv+/tIGAhthspEEy+qBDrrretjvAWoa1m6HTCJuHlKwcV0OrznDYzjRHzErPuHg5nSKOTCx33BsOcKc27DWJVt7joQKOzvswcvNS3dNx1nHSml2dOEv8cIuP7yFd0Ns6BsdjYd7JSHLYJyzB/4P3zSy8EzyJtAvt8q0eBWwMY95vYRKotjkJhObPEu2WVUXWXyf1pADyJp1an4dddVK7j/XZ51P1Ps+HugIMs2HDXSacdfB6jaWIvSSteQZzDioFEwn/B01J8gfUvizImwQl68PHFTzqF9Wup72sGTUAYDvDm/dR+85rx3VdmSnOfFyamecXUB7tHG/HDv4zWFp10GsS1Z1xl/DX5y1XGc4wLdzcHtjce2XUycL2zZKsTGUbNQ1ofxPL1vQuckpiczWAe5YqQAbP61C6bT6kgD//PTVTZsNpdQM12M91Mvi3AI7enUE2htRvYyjHEQ2jWuuX/pY8N4s8BJBaQBAYzAs9RgOeSs+SPK5flJe3XJDddyODg5vBTHD6z5N6zV3BhrLjWOTy50n/1CPLTbZPWOqZiSw0f1LEZNCr2ayClvUH/DQKTKmVCGa91WmDc2KW47h16+BZ5JbLf2MJeu8boGOoUClSDQ8XEhkKUPsptfA0nlZg5UPapdiu1OyITStaq4DZ0UsBbQbli3LoPI2jaY+fyGSR2E4Kh6dP7C8Tls9rsItONAAcYN0VdqoKAwcmaqF3s1SbbXPY2K5mEhfEJWTVX/1qtAgSKx/u4LVBKJmAAcfw8j2mfMH1thwLzneejEmO5HWBGxaGoOMlaa/0tsHtsaPhUCJ3J1lZJdaIyWsMR5PJdeqUq7giGlq3CpXk/ViPB/iMWhiW+0pV+8ehMk/DyJLQk4SmYyAsSree8+qGImWm1ewep/296t+gFmXciEQlkwy4r6G+INujOf+ESVwLVfZtXCvplXHunHGhTTGfsE/fxSoW6u
    bucket: jb-cadence-storage
    type: DEFAULT
description: ""
